/**
 * script.js — Pulsfi "Live Audit" demo page
 *
 * Same URL-param contract as before (?biz=&city=&cat=&phone=&report=),
 * generated by scraper.py's generate_demo_urls() — nothing about that
 * contract changed here, only what the page does with it.
 */

(function () {
  'use strict';

  const params = new URLSearchParams(window.location.search);
  const rawName = params.get('biz');
  const rawCity = params.get('city');
  const rawCat = params.get('cat');
  const rawPhone = params.get('phone');
  const rawReport = params.get('report');

  const category = formatCategoryTag(rawCat);
  const bizName = rawName ? rawName : 'Your Business';
  const city = rawCity ? rawCity : 'your area';

  let subName = 'your brand';
  if (rawName) {
    const words = rawName.split(' ');
    if (words.length > 0 && words[0].length > 2) subName = words[0];
  }

  // ------------------------------------------------------------
  // 1. Loading sequence — runs first, using the params we already
  //    have, so the "scan" text is personalised from frame one.
  // ------------------------------------------------------------
  runLoadingSequence(bizName, city, () => {
    injectDynamicContent();
    setupScrollReveals();
    setupCalendly();
    setupEngagementTracking();
  });

  function runLoadingSequence(name, cityName, done) {
    const loader = document.getElementById('loader');
    const linesEl = document.getElementById('loaderLines');
    const fillEl = document.getElementById('loaderBarFill');
    const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    // escapeHtml here specifically because these strings are inserted via
    // innerHTML below — this is the one place name/cityName need it;
    // everywhere else they're set via textContent, which is safe on its own.
    const safeName = escapeHtml(name);
    const safeCity = escapeHtml(cityName);
    const steps = [
      `Initializing report for ${safeName}…`,
      `Scanning local competitors in ${safeCity}…`,
      `Generating growth roadmap…`,
    ];

    if (reduceMotion || !loader || !linesEl || !fillEl) {
      if (loader) loader.classList.add('loader-hidden');
      done();
      return;
    }

    let stepIndex = 0;
    const stepDuration = 750; // ms per line, 3 lines ≈ 2.25s total

    function showNextLine() {
      if (stepIndex >= steps.length) {
        fillEl.style.width = '100%';
        setTimeout(() => {
          loader.classList.add('loader-hidden');
          done();
        }, 280);
        return;
      }
      const div = document.createElement('div');
      div.className = 'loader-line';
      div.innerHTML = `<span class="ok">✓</span>${steps[stepIndex]}`;
      linesEl.appendChild(div);
      requestAnimationFrame(() => div.classList.add('shown'));

      fillEl.style.width = `${Math.round(((stepIndex + 1) / steps.length) * 92)}%`;
      stepIndex += 1;
      setTimeout(showNextLine, stepDuration);
    }
    showNextLine();
  }

  // ------------------------------------------------------------
  // 2. Inject business/city/category text everywhere it belongs
  // ------------------------------------------------------------
  function injectDynamicContent() {
    const targets = {
      dynamicHeroName: bizName,
      dynamicHeroCity: city,
      dynamicSubName: subName,
      dynamicCity: city,
      dynamicAboutStrong: bizName,
      dynamicOpsCategory: category.toLowerCase() + ' services',
      dynamicOpsCity: city,
      dynamicCardCategory: category,
      dynamicCardCity: city,
      dynamicNoSiteCategory: category.toLowerCase() + ' business',
      dynamicNoSiteName: bizName,
      dynamicCostCategory: category.toLowerCase() + ' competitors',
      dynamicCostCity: city,
      dynamicFooterName: bizName,
    };
    for (const [id, value] of Object.entries(targets)) {
      const el = document.getElementById(id);
      if (el) el.textContent = value;
    }

    document.title = `${bizName} | Live Audit — Pulsfi`;

    const footerYear = document.getElementById('footerYear');
    if (footerYear) footerYear.textContent = new Date().getFullYear();

    if (rawPhone) {
      const phoneLink = document.getElementById('dynamicPhoneLink');
      if (phoneLink) {
        const cleanPhone = rawPhone.replace(/[^0-9+]/g, '');
        phoneLink.setAttribute('href', `tel:${cleanPhone}`);
        phoneLink.style.display = 'inline-flex';
      }
    }

    if (rawReport) {
      renderAuditReport(rawReport);
    } else {
      showNoSiteBranch();
    }
  }

  function showNoSiteBranch() {
    const noSite = document.getElementById('no-site-section');
    const statusLabel = document.getElementById('dynamicStatusLabel');
    if (noSite) noSite.style.display = 'block';
    if (statusLabel) statusLabel.textContent = 'No live site found';
  }

  // ------------------------------------------------------------
  // 3. Audit report: decode token, drive the radial gauge, list
  //    issues, and derive a category breakdown chart from the
  //    real issue titles (no fabricated data — every bar reflects
  //    an actual pass/fail from the report token).
  // ------------------------------------------------------------
  function renderAuditReport(token) {
    let report;
    try {
      const b64 = token.replace(/-/g, '+').replace(/_/g, '/');
      const binary = atob(b64);
      const bytes = Uint8Array.from(binary, (c) => c.charCodeAt(0));
      report = JSON.parse(new TextDecoder('utf-8').decode(bytes));
    } catch (e) {
      showNoSiteBranch();
      return;
    }

    const section = document.getElementById('audit-section');
    const scoreEl = document.getElementById('auditScore');
    const gradeEl = document.getElementById('auditGrade');
    const issuesEl = document.getElementById('auditIssues');
    const gaugeFill = document.getElementById('gaugeFill');
    const statusLabel = document.getElementById('dynamicStatusLabel');
    if (!section || !scoreEl || !issuesEl) return;

    const score = typeof report.score === 'number' ? report.score : 0;
    const grade = report.grade || '';
    const issues = report.issues || [];

    scoreEl.textContent = report.score != null ? report.score : '--';
    if (gradeEl) gradeEl.textContent = grade ? `Grade ${grade}` : '';
    if (statusLabel) statusLabel.textContent = issues.length ? `${issues.length} issue${issues.length === 1 ? '' : 's'} found` : 'Scan complete';

    // Gauge color follows the same pass/fail semantics as the rest of
    // the page: mint = healthy, amber = mid, coral = at risk.
    let gaugeColor = 'var(--mint)';
    if (score < 50) gaugeColor = 'var(--coral)';
    else if (score < 75) gaugeColor = 'var(--amber)';

    issuesEl.innerHTML = '';
    issues.forEach((issue) => {
      const li = document.createElement('li');
      li.className = 'audit-issue-item';
      li.innerHTML = `<span class="audit-issue-flag">⚠</span> ${escapeHtml(issue)}`;
      issuesEl.appendChild(li);
    });

    section.style.display = 'block';

    // Animate the gauge once the section actually scrolls into view,
    // not immediately (it's below the fold on first paint).
    const circumference = 2 * Math.PI * 90;
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        if (gaugeFill) {
          gaugeFill.style.stroke = gaugeColor;
          gaugeFill.style.strokeDashoffset = String(circumference * (1 - score / 100));
        }
        renderCategoryChart(issues);
        observer.disconnect();
      });
    }, { threshold: 0.3 });
    observer.observe(section);
  }

  /**
   * Buckets the report's real issue titles into 5 categories using
   * keyword matching, so the breakdown chart is derived entirely from
   * genuine audit data — nothing here is fabricated or illustrative.
   */
  function renderCategoryChart(issues) {
    const container = document.getElementById('auditChartRows');
    if (!container) return;

    const lowerIssues = issues.map((i) => i.toLowerCase());
    const categories = [
      { label: 'Security', keywords: ['ssl', 'secure', 'https'] },
      { label: 'Speed', keywords: ['load', 'slow', 'sluggish', 'speed', 'response', 'timeout'] },
      { label: 'Mobile', keywords: ['mobile', 'responsive', 'viewport'] },
      { label: 'SEO', keywords: ['title', 'meta', 'heading', 'h1', 'seo'] },
      { label: 'Trust signals', keywords: ['favicon', 'social', 'og:', 'preview'] },
    ];

    container.innerHTML = '';
    categories.forEach((cat) => {
      const failed = lowerIssues.some((issue) => cat.keywords.some((kw) => issue.includes(kw)));
      const row = document.createElement('div');
      row.className = 'chart-row';
      row.innerHTML = `
        <span class="chart-label">${cat.label}</span>
        <span class="chart-track"><span class="chart-fill ${failed ? 'fail' : 'pass'}" style="width:0%"></span></span>
        <span class="chart-status ${failed ? 'fail' : 'pass'}">${failed ? 'FAIL' : 'PASS'}</span>
      `;
      container.appendChild(row);
      const fill = row.querySelector('.chart-fill');
      requestAnimationFrame(() => {
        fill.style.width = failed ? '32%' : '96%';
      });
    });
  }

  // ------------------------------------------------------------
  // 4. Scroll reveals
  // ------------------------------------------------------------
  function setupScrollReveals() {
    const revealEls = document.querySelectorAll('.reveal');
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('in-view');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.12, rootMargin: '0px 0px -40px 0px' }
    );
    revealEls.forEach((el) => observer.observe(el));
  }

  // ------------------------------------------------------------
  // 5. Calendly lifecycle — hide the skeleton once the widget
  //    actually renders, and fall back gracefully (e.g. blocked by
  //    an ad/tracker blocker) instead of leaving a dead loading state.
  // ------------------------------------------------------------
  function setupCalendly() {
    const skeleton = document.getElementById('calendlySkeleton');
    if (!skeleton) return;

    let resolved = false;
    const resolve = () => {
      if (resolved) return;
      resolved = true;
      skeleton.style.display = 'none';
    };

    window.addEventListener('message', (e) => {
      if (typeof e.data === 'object' && e.data && String(e.data.event || '').indexOf('calendly') === 0) {
        resolve();
      }
    });

    // Fallback: if Calendly's widget script never loads/renders (blocked,
    // offline, etc.), stop showing a perpetual loading shimmer and just
    // point people at the "open in a new tab" link instead.
    setTimeout(() => {
      if (resolved) return;
      const iframeLoaded = document.querySelector('.calendly-inline-widget iframe');
      if (iframeLoaded) {
        resolve();
      } else {
        skeleton.textContent = 'Calendar unavailable here — use the link below';
      }
    }, 6000);
  }

  // ------------------------------------------------------------
  // 6. Hot-lead engagement tracking — fire-and-forget beacon, no
  //    effect on page function if PULSFI_TRACK_ENDPOINT is unset or
  //    unreachable. See index.html's <head> for setup notes.
  // ------------------------------------------------------------
  function setupEngagementTracking() {
    const endpoint = window.PULSFI_TRACK_ENDPOINT;
    if (!endpoint) return; // tracking disabled — nothing else in the page depends on this

    const payload = { biz: rawName || '', city: rawCity || '', cat: rawCat || '', phone: rawPhone || '' };
    const firedEvents = new Set();

    function beacon(event) {
      // Each event type fires at most once per page load — a visitor
      // re-triggering the same signal isn't a stronger signal.
      if (firedEvents.has(event)) return;
      firedEvents.add(event);
      try {
        const body = JSON.stringify({ ...payload, event });
        if (navigator.sendBeacon) {
          // IMPORTANT: sendBeacon with a Blob typed 'application/json' is
          // NOT a CORS-safelisted content type, which forces a preflight —
          // and in practice the actual beacon POST silently never follows
          // through after that preflight in Chromium. 'text/plain' is
          // CORS-safelisted (no preflight needed), and the Flask endpoint
          // parses the body as JSON regardless of the declared type.
          const blob = new Blob([body], { type: 'text/plain' });
          navigator.sendBeacon(endpoint, blob);
        } else {
          fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body, keepalive: true }).catch(() => {});
        }
      } catch (e) {
        // Tracking must never be able to break the page.
      }
    }

    beacon('page_view');

    // Real intent signals, not scroll position — the booking widget is
    // always visible in the sticky left panel, so "scrolled into view"
    // would fire on nearly every page load and mean nothing. Calendly's
    // own postMessage events are the real signal:
    //   - date_and_time_selected → visitor is actively booking (strong intent)
    //   - event_scheduled        → visitor actually booked (the whole point)
    window.addEventListener('message', (e) => {
      const evtName = typeof e.data === 'object' && e.data ? String(e.data.event || '') : '';
      if (evtName === 'calendly.date_and_time_selected') beacon('booking_intent');
      if (evtName === 'calendly.event_scheduled') beacon('booking_confirmed');
    });

    // Backup weak signal: clicking a CTA that jumps to the booking panel.
    document.querySelectorAll('a[href="#bookingEmbed"]').forEach((el) => {
      el.addEventListener('click', () => beacon('booking_intent'));
    });
  }

  // ------------------------------------------------------------
  // Utilities
  // ------------------------------------------------------------
  function formatCategoryTag(rawCat) {
    if (!rawCat) return 'Local Business';
    let val = rawCat.includes('=') ? rawCat.split('=')[1] : rawCat;
    val = val.replace(/_/g, ' ');
    val = val
      .split(' ')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join(' ');
    return val || 'Local Business';
  }

  function escapeHtml(unsafe) {
    if (!unsafe) return '';
    return unsafe
      .toString()
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
})();
