"""
suppression_list.py — CAN-SPAM compliant opt-out / do-not-contact list.

US commercial email law (CAN-SPAM Act) requires two things this codebase
did not actually have before this module:

  1. A functioning opt-out mechanism — the old code put "reply unsubscribe"
     in the footer, but nothing ever read those replies. It was a promise
     with no enforcement, which is not compliant and (more practically)
     means a business that asked to stop hearing from you could get
     re-emailed the next time it's re-scraped.
  2. Opt-outs must be honored "promptly" (10 business days is the legal
     ceiling, but there's no reason not to make it instant).

This module makes the promise real:
  • A one-click unsubscribe LINK (not a reply) — the standard, actually-
    enforced pattern every legitimate ESP uses. The link hits
    ``/api/unsubscribe?email=...&token=...`` on your own API.
  • A signed token (HMAC over the email + a server secret) so the link
    can't be used to unsubscribe an address the recipient doesn't own —
    someone can't grief a competitor by mass-unsubscribing their leads.
  • email_sender.py checks this list and SKIPS suppressed addresses
    before ever calling send_email — enforced at the source, not just
    documented.

Storage: SQLite, same short-lived-connection/WAL pattern as db.py and
leads_cache.py, so it's consistent with the rest of the codebase and
safe across the API's request + background send threads.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import sqlite3
import time
from pathlib import Path

from config import DATA_DIR, GMAIL_APP_PASSWORD

logger = logging.getLogger(__name__)

DB_PATH: Path = DATA_DIR / "suppression.db"

# HMAC secret for unsubscribe tokens. Derived from the Gmail app password
# (already a private secret you control) rather than requiring yet another
# env var — good enough for signing a low-stakes, single-purpose token.
_SECRET = (GMAIL_APP_PASSWORD or "leadgen-fallback-secret").encode("utf-8")


def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH, timeout=10)
    conn.execute("PRAGMA journal_mode=WAL;")
    conn.execute("PRAGMA busy_timeout=10000;")
    return conn


def init_suppression_list() -> None:
    """Create the table if absent. Idempotent; call on API startup."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with _connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS suppressed (
                email      TEXT PRIMARY KEY,
                reason     TEXT NOT NULL DEFAULT 'unsubscribe',
                created_at REAL NOT NULL
            )
            """
        )
    logger.info("Suppression list ready at %s", DB_PATH)


def unsubscribe_token(email: str) -> str:
    """Signed token proving an unsubscribe link was generated by us for
    this exact address — prevents third parties from unsubscribing
    addresses they don't control.
    """
    norm = email.strip().lower()
    return hmac.new(_SECRET, norm.encode("utf-8"), hashlib.sha256).hexdigest()[:32]


def verify_token(email: str, token: str) -> bool:
    """Constant-time comparison to avoid timing side-channels."""
    return hmac.compare_digest(unsubscribe_token(email), token or "")


def is_suppressed(email: str) -> bool:
    """True if this address has opted out and must never be emailed."""
    norm = (email or "").strip().lower()
    if not norm:
        return False
    with _connect() as conn:
        row = conn.execute(
            "SELECT 1 FROM suppressed WHERE email = ?", (norm,)
        ).fetchone()
    return row is not None


def add_suppression(email: str, reason: str = "unsubscribe") -> None:
    """Add an address to the do-not-contact list. Idempotent."""
    norm = (email or "").strip().lower()
    if not norm:
        return
    with _connect() as conn:
        conn.execute(
            "INSERT OR REPLACE INTO suppressed (email, reason, created_at) VALUES (?, ?, ?)",
            (norm, reason, time.time()),
        )
    logger.info("Suppressed %s (reason=%s) — will never be emailed again.", norm, reason)


def remove_suppression(email: str) -> bool:
    """Manually re-permit an address (e.g. an accidental unsubscribe
    reported by the recipient). Returns True if a row was removed.
    """
    norm = (email or "").strip().lower()
    with _connect() as conn:
        cur = conn.execute("DELETE FROM suppressed WHERE email = ?", (norm,))
        return cur.rowcount > 0


def suppression_count() -> int:
    with _connect() as conn:
        return conn.execute("SELECT COUNT(*) FROM suppressed").fetchone()[0]
